[package]
name = "css-rtl-compiler"
version = "0.1.0"
edition = "2021"

description = "Convert CSS files into an RTL-compatible version"

license = "Apache-2.0"

include = ["src/*.rs", "README.md", "LICENSE"]

[dependencies]
